### ISSUE TITLE
Integrate with projecthydra-labs/rdf-vocab?

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/rdf-fcrepo4#2]
https://github.com/projecthydra-labs/rdf-vocab/tree/master/lib/rdf-vocab/vocab

See also:
- https://github.com/projecthydra-labs/rdf-vocab/blob/master/lib/rdf-vocab/vocab/fcrepo3.rb

Related concerns:
- projecthydra-labs/rdf-vocab#20
- projecthydra-labs/rdf-vocab#7
- projecthydra-labs/rdf-vocab#19

**Comment by ndushay** [comment]
or, remove in favor of (pull requests to?) projecthydra-labs/rdf-vocab?  (which is now at  ruby-rdf/rdf-vocab  i think)

**Comment by ndushay** [comment]
this is covered by #3 - in progress.
